fun main() {
    println("Set - Inmutable")
    val idsMascotas = setOf(1, 2, 3, 4, 8, 4, 1, 3)
    println("ids set: ${idsMascotas}")
    println("Operaciones de conjuntos")
    val perros = setOf("Firulais", "Rex", "Toby", "Max")
    val gatos = setOf("Mishi", "Toby", "Luna", "Max")
    println("perros set: ${perros}")
    println("gatos set: ${gatos}")
    println("union: ${perros union gatos}")
    println("interseccion: ${perros intersect gatos}")
    println("substraccion: ${perros subtract gatos}")
    println("perros set: ${perros}")
    println("gatos set: ${gatos}")

    println("Set - Mutable")
    val especies = mutableSetOf("Perro", "Gato", "Conejo")
    println(especies)
    especies.add("perro")
    println(especies)
    especies.add("Hamster")
    println(especies)
    especies.remove("Conejo")
    println(especies)
    println("Verificar si elemento existe ${"Perro" in especies}")
    println("Verificar si elemento existe ${"Conejo" in especies}")
}
